export { default as FyInput } from './Default/index';
export { default as FyInputCep } from './Cep/index.vue';
export { default as FyInputCnpj } from './Cnpj/index.vue';
export { default as FyInputCpf } from './Cpf/index.vue';
export { default as FyInputCurrency } from './Currency/index.vue';
export { default as FyInputDate } from './Date/index.vue';
export { default as FyInputDateTime } from './DateTime/index.vue';
export { default as FyInputPhone } from './Phone/index.vue';
export { default as FyInputTime } from './Time/index.vue';
