import { VueConstructor } from 'vue';

export const FyAutocomplete: VueConstructor;
export const FyButton: VueConstructor;
export const FyNoticationBar: VueConstructor;
export const FyInfoCard: VueConstructor;
export const FyUserLabel: VueConstructor;
export const FyDataTable: VueConstructor;
export const FyInputCpf: VueConstructor;
export const FyInputCnpj: VueConstructor;
export const FyInputPhone: VueConstructor;
export const FyInputCep: VueConstructor;
export const FyInput: VueConstructor;
export const FyInputDate: VueConstructor;
export const FyInputTime: VueConstructor;
export const FyInputDateTime: VueConstructor;
export const FyInputCurrency: VueConstructor;
export const FyDialog: VueConstructor;
export const FyDialogDelete: VueConstructor;
export const FyDrawer: VueConstructor;
export const FySnackbar: VueConstructor;
export const FyToolbar: VueConstructor;
export const FyFilterData: VueConstructor;
export const FyGaugeChart: VueConstructor;
