name: Publish
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Run linters
        env:
          COMPONENTS_TOKEN: ${{ secrets.TOKEN_ACCESS }}
        run: npm run lint

      - uses: actions/checkout@v2

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
          
      - run: npm ci
      - run: npm run build:npm
      - run: npm publish
        env:
          COMPONENTS_TOKEN: ${{ secrets.TOKEN_ACCESS }}
